#!/usr/bin/env bash
set -e
command=$1
shift

sudo -v

get_packages_to_remove () {
    packages=$1
    deborphan --guess-all -k <(echo "$packages")
    deborphan --guess-all --find-config -k <(echo "$packages")
}

case "$command" in
    desc)
        package=$1
        desc=$(aptitude show "$package" | grep '^Description: ')
        echo "${desc:13:120}"
        ;;

    diff)
        packages=$1
        diff=$(comm -23 <(aptitude search '?installed !?automatic' | cut -b 4- | cut -d ' ' -f1 | sort) <(echo "$packages" | sort))
        echo "$diff"
        ;;

    install)
        packages=$1
        sudo aptitude -q=3 install "$packages"
        ;;

    sync)
        packages=$1
        missing=$(comm -23 <(echo "$packages" | sed 's/ /\n/g' | sort) <(dpkg-query -f '${binary:Package}\n' -W | sed 's/:amd64//g' | sort))
        if [ ! -z "$missing" ]
        then
            sudo aptitude -q=3 install "$missing"
        fi
        to_remove=$(get_packages_to_remove "$packages")
        if [ ! -z "$to_remove" ]
        then
            to_remove=$(sudo apt-get -qq -s purge "$to_remove" 2>/dev/null | cut -f2 -d ' ')
            if [ ! -z "$to_remove" ]
            then
                sudo aptitude -q=3 purge "$to_remove"
            fi
        fi
        ;;

    uninstall)
        packages=$1
        sudo aptitude purge "$packages"
        ;;

    update)
        packages=$1
        sudo apt-get -q install "$packages"
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 2
        ;;

esac
