#!/usr/bin/env bash
set -e

apt_get_install () {
    if [[ -n "${ALWAYS_ANSWER:-}" ]]
    then
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y install "$@"
    else
        sudo apt-get install "$@"
    fi
}

apt_get_purge () {
    if [[ -n "${ALWAYS_ANSWER:-}" ]]
    then
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y purge "$@"
    else
        sudo apt-get purge "$@"
    fi
}

command=$1
shift || return 0
case "$command" in

    desc)
        package=$1
        desc=$(apt-cache show "$package" | grep -m1 '^Description: ' 2>/dev/null || true)
        echo "${desc:13:120}"
        ;;

    diff)
        diff=$(comm -23 <(apt-mark showmanual | sort) <(echo "$@" | sort))
        echo "$diff"
        ;;

    install)
        apt_get_install "$@"
        ;;

    sync)
        packages=$(printf '%s\n' "$@" | sort | uniq)
        already_installed=$(dpkg-query -W -f='${binary:Package}\t${db:Status-Abbrev}\n' | awk '$2 ~ /^ii/ { sub(/:[^:]+$/, "", $1); print $1 }' | sort)
        readarray -t not_installed < <(comm -23 <(echo "$packages") <(echo "$already_installed"))
        if [[ "${#not_installed[@]}" -gt 0 ]]
        then
            available=$(apt-cache pkgnames | sort)
            readarray -t not_found < <(comm -23 <(printf '%s\n' "${not_installed[@]}") <(echo "$available"))
            [[ "${#not_found[@]}" == 0 ]] || error "Packages not found: ${not_found[*]}"
            readarray -t to_install < <(comm -12 <(printf '%s\n' "${not_installed[@]}") <(echo "$available"))
            [[ "${#to_install[@]}" == 0 ]] || apt_get_install "${to_install[@]}"
        fi
        ;;

    uninstall)
        apt_get_purge "$@"
        ;;

    update)
        sudo apt-get -q install "$@"
        ;;

    *)
        error_and_exit "Module does not support this command"
        ;;

esac
