#!/usr/bin/env bash
set -e

get_packages_to_remove () {
    tmp=$(mktemp)
    echo "$1" > "$tmp"
    deborphan --guess-all --keep-file="$tmp"
    deborphan --guess-all --find-config --keep-file="$tmp"
    rm "$tmp"
}

ask_to_install_if_not_found aptitude && sudo apt-get install aptitude
ask_to_install_if_not_found dpkg && sudo apt-get install dpkg

command=$1
shift || return 0
case "$command" in

    desc)
        package=$1
        desc=$(aptitude show "$package" | grep '^Description: ')
        echo "${desc:13:120}"
        ;;

    diff)
        diff=$(comm -23 <(aptitude search '?installed !?automatic' | cut -b 4- | cut -d ' ' -f1 | sort) <(echo "$@" | sort))
        echo "$diff"
        ;;

    install)
        sudo aptitude -q=3 install "$@"
        ;;

    sync)
        packages=$(printf '%s\n' "$@" | sort | uniq)
        already_installed=$(dpkg --get-selections | grep -v deinstall | sed 's/:amd64//g' | awk '{print $1}' | sort)
        readarray -t missing < <(comm -23 <(echo "$packages") <(echo "$already_installed"))
        [[ "${#missing[@]}" == 0 ]] || sudo aptitude -q=3 install "${missing[@]}"
        if command -v deborphan >/dev/null 2>/dev/null
        then
            readarray -t to_remove < <(get_packages_to_remove "$packages")
            if [[ "${#to_remove[@]}" -gt 0 ]]
            then
                readarray -t to_remove < <(sudo apt-get -qq -s purge "${to_remove[@]}" 2>/dev/null | cut -f2 -d ' ')
                [[ "${#to_remove[@]}" == 0 ]] || sudo aptitude -q=3 purge "${to_remove[@]}" || true
            fi
        fi
        ;;

    uninstall)
        sudo aptitude purge "$@"
        ;;

    update)
        sudo apt-get -q install "$@"
        ;;

    *)
        error_and_exit "Module does not support this command"
        ;;

esac
