#!/usr/bin/env bash
set -e
command=$1
shift

case "$command" in

    bootstrap)
        sudo apt-get install cabal-install
        ;;

    desc)
        package=$1
        desc=$(cabal info "$package" | grep '^    Synopsis:      ')
        echo "${desc:19:120}"
        ;;

    install)
        packages=$1
        cabal update
        already_installed=$(cabal list --installed)
        for p in $packages
        do
            if ! echo "$already_installed" | grep "^* $p$" >/dev/null
            then
                if ! TMPDIR=$XDG_RUNTIME_DIR cabal install "$p"
                then
                    break
                fi
            fi
        done
        ;;

    sync)
        packages=$1
        cabal update
        already_installed=$(cabal list --installed)
        for p in $packages
        do
            if ! echo "$already_installed" | grep "^* $p$" >/dev/null
            then
                if ! TMPDIR=$XDG_RUNTIME_DIR cabal install "$p"
                then
                    break
                fi
            fi
        done
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 2
        ;;

esac
