#!/usr/bin/env bash
set -e

command=$1
shift || true
case "$command" in

    bootstrap)
        if ! which cargo >/dev/null 2>/dev/null
        then
            if sudo -l -n
            then
                sudo apt-get install cargo
            else
                curl -s https://static.rust-lang.org/rustup.sh | sh - --disable-sudo --prefix="$HOME/.local"
            fi
        fi
        ;;

    desc)
        echo
        ;;

    install)
        already_installed=$(cargo install --list)
        for p in "$@"
        do
            if ! echo "$already_installed" | grep "^$p " >/dev/null
            then
                if ! TMPDIR=$XDG_RUNTIME_DIR cargo install "$p"
                then
                    break
                fi
            fi
        done
        ;;

    sync)
        already_installed=$(cargo install --list)
        for p in "$@"
        do
            if ! echo "$already_installed" | grep "^$p " >/dev/null
            then
                if ! TMPDIR=$XDG_RUNTIME_DIR cargo install "$p"
                then
                    break
                fi
            fi
        done
        ;;

    uninstall)
        for p in "$@"
        do
            cargo uninstall "$p"
        done
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 2
        ;;

esac
