#!/usr/bin/env bash
set -e
command=$1
shift

case "$command" in
    desc)
        echo
        ;;

    install)
        packages=$1
        already_installed=$(cargo install --list)
        for p in $packages
        do
            if ! echo "$already_installed" | grep "^$p " >/dev/null
            then
                if ! TMPDIR=$XDG_RUNTIME_DIR cargo install "$p"
                then
                    break
                fi
            fi
        done
        ;;

    sync)
        packages=$1
        already_installed=$(cargo install --list)
        for p in $packages
        do
            if ! echo "$already_installed" | grep "^$p " >/dev/null
            then
                if ! TMPDIR=$XDG_RUNTIME_DIR cargo install "$p"
                then
                    break
                fi
            fi
        done
        ;;

    uninstall)
        packages=$1
        for p in $packages
        do
            cargo uninstall "$p"
        done
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 2
        ;;

esac
