#!/usr/bin/env bash
# -*- mode: sh; -*-

command=$1
shift

case "$command" in
    desc)
        echo
        ;;

    install)
        go get "$@"
        ;;

    sync)
        go get "$@"
        ;;

    uninstall)
        go clean -i "$@"
        ;;

    update)
        go get -u "$@"
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 1
        ;;

esac
