#!/usr/bin/env bash
set -e
command=$1
shift

case "$command" in
    desc)
        echo
        ;;

    install)
        packages=$1
        npm install -g "$packages"
        ;;

    sync)
        packages=$1
        for p in $packages
        do
            if ! npm list -g "$p" >/dev/null 2>/dev/null
            then
                npm install -g "$p"
            fi
        done
        ;;

    uninstall)
        packages=$1
        npm uninstall -g "$packages"
        ;;

    update)
        packages=$1
        npm update "$packages"
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 2
        ;;

esac
