#!/usr/bin/env bash
set -e

command=$1
shift || true
case "$command" in

    bootstrap)
        if ! which npm >/dev/null 2>/dev/null
        then
            sudo apt-get install npm
        fi
        ;;

    desc)
        echo
        ;;

    install)
        npm install -g "$@"
        ;;

    sync)
        for p in "$@"
        do
            if ! npm list -g "$p" >/dev/null 2>/dev/null
            then
                npm install -g "$p"
            fi
        done
        ;;

    uninstall)
        npm uninstall -g "$@"
        ;;

    update)
        npm update "$@"
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 2
        ;;

esac
