#!/usr/bin/env bash
set -e
sysypip=pip2
sysypython=python2

sysypath=$(realpath "$confdir/bin/..")
tagsfile=$confdir/tags

# shellcheck source=/home/sven/sync/sysy/modules/pip3
source "$sysypath/modules/pip3" "$@"
