#!/usr/bin/env bash
set -e
command=$1
shift

case "$command" in

    bootstrap)
        sudo apt-get install python2
        curl -s https://bootstrap.pypa.io/get-pip.py | python2 - --user
        ;;

    desc)
        echo
        ;;

    install)
        packages=$1
        pip2 install --user "$packages"
        ;;

    sync)
        packages=$1
        pip2 install --user "$packages"
        ;;

    uninstall)
        packages=$1
        pip2 uninstall "$packages"
        ;;

    update)
        packages=$1
        pip2 install --user --upgrade "$packages"
        ;;

    *)
        echo "Module does not support this command" 1>&2
        exit 2
        ;;

esac
