#!/usr/bin/env bash
set -e

[[ -n "$sysypip" ]] || sysypip=pip3
[[ -n "$sysypython" ]] || sysypython=pip3

ask_to_install_if_not_found "$sysypython" && sudo apt-get install "$sysypython"
ask_to_install_if_not_found "$sysypip" && (curl -s https://bootstrap.pypa.io/get-pip.py | "$sysypython" - --user)

command=$1
shift || return 0
case "$command" in

    desc)
        echo
        ;;

    install)
        "$sysypip" install --user "$@"
        ;;

    sync)
        # strip git repository paths and normalize package names
        packages=$(printf '%s\n' "$@" \
                       | sed 's/^git+[a-zA-Z0-9.:\/_\-]*\/\([^\/@]*\)\(@[0-9a-fA-F]*\)\?$/\1/g' \
                       | sed 's/^\(.*\)\.git$/\1/g' \
                       | sed 's/[-_.]/-/g' \
                       | tr '[:upper:]' '[:lower:]' \
                       | sort \
                       | uniq)
        already_installed=$("$sysypip" list \
                                | cut -d' ' -f1 \
                                | sed 's/[-_.]/-/g' \
                                | tr '[:upper:]' '[:lower:]' \
                                | sort)
        readarray -t missing < <(comm -23 <(echo "$packages") <(echo "$already_installed"))
        [[ "${#missing[@]}" == 0 ]] || "$sysypip" install --user "$@" # use all packages since we stripped all git paths
        ;;

    uninstall)
        "$sysypip" uninstall "$@"
        ;;

    update)
        "$sysypip" install --user --upgrade "$@"
        ;;

    *)
        error_and_exit "Module does not support this command"
        ;;

esac
