#!/usr/bin/env bash
set -e

ensure_uv () {
    if ask_to_install_if_not_found uv
    then
        (curl -LsSf https://astral.sh/uv/install.sh | sh) || error_and_exit "Could not install uv"
    fi
}

command=$1
shift || return 0
case "$command" in

    desc)
        echo
        ;;

    install)
        ensure_uv
        for package in "$@"
        do
            # shellcheck disable=SC2086
            uv tool install $package
        done
        ;;

    sync)
        ensure_uv
        for package in "$@"
        do
            # shellcheck disable=SC2086
            uv tool install $package
        done
        ;;

    uninstall)
        ensure_uv
        uv tool uninstall "$@"
        ;;

    update)
        ensure_uv
        for package in "$@"
        do
            uv tool upgrade "${package##* }"
        done
        ;;

    *)
        error_and_exit "Module does not support this command"
        ;;

esac
