#!/usr/bin/env bash
set -e

ensure_uv () {
    if ask_to_install_if_not_found uv
    then
        (curl -LsSf https://astral.sh/uv/install.sh | sh) || error_and_exit "Could not install uv"
    fi
}

tool_name () {
    local package=$1
    package=${package##* }
    sed -E 's/(\[|[=<>!~]).*$//' <<< "$package"
}

list_installed_tools () {
    uv tool list | awk '/^[^[:space:]]/ { print $1 }' | sort
}

command=$1
shift || return 0
case "$command" in

    desc)
        echo
        ;;

    install)
        ensure_uv
        for package in "$@"
        do
            # shellcheck disable=SC2086
            uv tool install $package
        done
        ;;

    sync)
        ensure_uv
        declare -A packages
        for package in "$@"
        do
            packages[$(tool_name "$package")]=$package
        done
        already_installed=$(list_installed_tools)
        readarray -t missing < <(comm -23 <(printf '%s\n' "${!packages[@]}" | sort) <(echo "$already_installed"))
        for package in "${missing[@]}"
        do
            # shellcheck disable=SC2086
            uv tool install ${packages[${package}]}
        done
        ;;

    uninstall)
        ensure_uv
        uv tool uninstall "$@"
        ;;

    update)
        ensure_uv
        for package in "$@"
        do
            uv tool upgrade "${package##* }"
        done
        ;;

    *)
        error_and_exit "Module does not support this command"
        ;;

esac
